USE BanHangDienThoai
GO

--| =================================================> Toa Khoa Ngoai <=================================================|

-- Tạo RBTV Khóa ngoại SANPHAM
ALTER TABLE dbo.SANPHAM 
	ADD CONSTRAINT FRK_SANPHAM_LOAISP 
	FOREIGN KEY(MALOAI) 
	REFERENCES dbo.LOAISP(MALOAI) 	
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.SANPHAM 
	ADD CONSTRAINT FRK_SANPHAM_NHASX 
	FOREIGN KEY(MASX) 
	REFERENCES dbo.NHASX(MASX)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO


-- Tao RBTV Khoa Ngoai CTSP
ALTER TABLE dbo.CTSP
	ADD CONSTRAINT FRK_CTSP_SANPHAM
	FOREIGN KEY(MASP)
	REFERENCES dbo.SANPHAM(MASP)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

-- sp_helpconstraint DONDH
-- Tạo RBTV khóa ngoại DONDH
ALTER TABLE dbo.DONDH 
	ADD CONSTRAINT FRK_DONDH_MAKH 
	FOREIGN KEY(MAKH) 
	REFERENCES dbo.KHACHHANG(MAKH)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.DONDH
	ADD CONSTRAINT FRK_DONDH_NHANVIEN
	FOREIGN KEY(MANV)
	REFERENCES dbo.NHANVIEN(MANV)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO


-- Tạo RBTV Khóa ngoại CTDH
ALTER TABLE dbo.CTDH 
	ADD CONSTRAINT FRK_CTDH_SANPHAM 
	FOREIGN KEY(MASP) 
	REFERENCES dbo.SANPHAM(MASP)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.CTDH 
	ADD CONSTRAINT FRK_CTDH_DONDH 
	FOREIGN KEY(MADH) 
	REFERENCES dbo.DONDH(MADH)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO


-- Tạo RBTV Khóa ngoại PHIEUNHAP
ALTER TABLE dbo.PHIEUNHAP 
	ADD CONSTRAINT FRK_PHIEUNHAP_NHANVIEN 
	FOREIGN KEY(MANV) 
	REFERENCES dbo.NHANVIEN(MANV)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.PHIEUNHAP 
	ADD CONSTRAINT FRK_PHIEUNHAP_MACC 
	FOREIGN KEY(MACC) 
	REFERENCES dbo.NHACC(MACC)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

-- Tạo RBTV Khóa ngoại CTPN
ALTER TABLE dbo.CTPN 
	ADD CONSTRAINT FRK_CTPN_PHIEUNHAP 
	FOREIGN KEY(MAPN) 
	REFERENCES dbo.PHIEUNHAP(MAPN)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.CTPN 
	ADD CONSTRAINT FRK_CTPN_SANPHAM 
	FOREIGN KEY(MASP) 
	REFERENCES dbo.SANPHAM(MASP)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
GO

-- Tạo RBTV Khóa ngoại PHIEUXUAT
ALTER TABLE dbo.PHIEUXUAT 
	ADD CONSTRAINT FRK_PHIEUXUAT_NHANVIEN 
	FOREIGN KEY(MANV) 
	REFERENCES dbo.NHANVIEN(MANV)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.PHIEUXUAT 
	ADD CONSTRAINT FRK_PHIEUXUAT_KHACHHANG 
	FOREIGN KEY(MAKH) 
	REFERENCES dbo.KHACHHANG(MAKH)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.PHIEUXUAT
	ADD CONSTRAINT FRK_PHIEUXUAT_DONDH
	FOREIGN KEY(MADH)
	REFERENCES dbo.DONDH(MADH)
	--ON UPDATE CASCADE
	--ON DELETE NO ACTION
GO

-- Tạo RBTV Khóa ngoại CTPX
ALTER TABLE dbo.CTPX 
	ADD CONSTRAINT FRK_CTPX_PHIEUXUAT 
	FOREIGN KEY(MAPX) 
	REFERENCES dbo.PHIEUXUAT(MAPX)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

ALTER TABLE dbo.CTPX 
	ADD CONSTRAINT FRK_CTPX_SANPHAM 
	FOREIGN KEY(MASP) 
	REFERENCES dbo.SANPHAM(MASP)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO


-- Tao RBTV khoa ngoai cho bang TONKHO
ALTER TABLE TONKHO 
	ADD CONSTRAINT FRK_TONKHO_SANPHAM 
	FOREIGN KEY(MASP) 
	REFERENCES dbo.SANPHAM(MASP)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

-- Tao RBTV khoa ngoai cho bang Account
ALTER TABLE dbo.Account
	ADD CONSTRAINT FRK_Account_NHANVIEN
	FOREIGN KEY(UserId)
	REFERENCES dbo.NHANVIEN(MANV)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

-- Tao RBTV khoa ngoai cho bang Permission
ALTER TABLE dbo.Permission
	ADD CONSTRAINT FRK_Permission_Business
	FOREIGN KEY(BusinessId)
	REFERENCES dbo.Business(BusinessId)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO

-- Tao RBTV khoa ngoai cho bang GrantPermission
ALTER TABLE dbo.GrantPermission
	ADD CONSTRAINT	FRK_GrantPermission_Account
	FOREIGN KEY (UserId)
	REFERENCES dbo.Account(UserId)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
go

ALTER TABLE dbo.GrantPermission
	ADD CONSTRAINT FRK_GrantPermission_Permission
	FOREIGN KEY (PermissionId)
	REFERENCES dbo.Permission (PermissionId)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO


-- Tao RBTV khoa ngoai cho bang PermisisonAction
ALTER TABLE dbo.PermissionAction
	ADD CONSTRAINT FRK_PermisisonAction_Permission
	FOREIGN KEY (PermissionId)
	REFERENCES dbo.Permission(PermissionId)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
GO
