//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTCN
    {
        public string MAQH { get; set; }
        public Nullable<bool> DANHMUC { get; set; }
        public Nullable<bool> QUANLYBANHANG { get; set; }
        public Nullable<bool> THONGKE { get; set; }
        public Nullable<bool> SAOLUU { get; set; }
        public Nullable<bool> HELP { get; set; }
    }
}
