//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public int MADH { get; set; }
        public int MASP { get; set; }
        public Nullable<int> SLDH { get; set; }
    
        public virtual DONDH DONDH { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
