//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPQ
    {
        public int ID { get; set; }
        public string MAQH { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHANQUYEN PHANQUYEN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
