//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPX
    {
        public int MAPX { get; set; }
        public int MASP { get; set; }
        public Nullable<int> SLX { get; set; }
        public Nullable<float> PHANTRAM { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
