//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBANHANGEntities : DbContext
    {
        public QLBANHANGEntities()
            : base("name=QLBANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTCN> CTCNs { get; set; }
        public virtual DbSet<CTDH> CTDHs { get; set; }
        public virtual DbSet<CTPN> CTPNs { get; set; }
        public virtual DbSet<CTPQ> CTPQs { get; set; }
        public virtual DbSet<CTPX> CTPXes { get; set; }
        public virtual DbSet<DONDH> DONDHs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHACC> NHACCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHASX> NHASXes { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TONKHO> TONKHOes { get; set; }
        public virtual DbSet<vw_DanhSachDonDatHang> vw_DanhSachDonDatHang { get; set; }
        public virtual DbSet<vw_DanhSachDonDh> vw_DanhSachDonDh { get; set; }
        public virtual DbSet<vw_DanhSachKhachHang> vw_DanhSachKhachHang { get; set; }
        public virtual DbSet<vw_DanhSachLoaiSanPham> vw_DanhSachLoaiSanPham { get; set; }
        public virtual DbSet<vw_DanhSachNhaCungCap> vw_DanhSachNhaCungCap { get; set; }
        public virtual DbSet<vw_DanhSachNhanVien> vw_DanhSachNhanVien { get; set; }
        public virtual DbSet<vw_DanhSachNhaSanXuat> vw_DanhSachNhaSanXuat { get; set; }
        public virtual DbSet<vw_DanhSachPhieuNhap> vw_DanhSachPhieuNhap { get; set; }
        public virtual DbSet<vw_DanhSachPhieuXuat> vw_DanhSachPhieuXuat { get; set; }
        public virtual DbSet<vw_DanhSachSanPhams> vw_DanhSachSanPhams { get; set; }
        public virtual DbSet<vw_NhaCungCap> vw_NhaCungCap { get; set; }
        public virtual DbSet<vw_PhieuXuatKhachHang> vw_PhieuXuatKhachHang { get; set; }
        public virtual DbSet<vw_ThongKeDonDatHang> vw_ThongKeDonDatHang { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachhPhieuNhap_Result> sp_DanhSachhPhieuNhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachhPhieuNhap_Result>("sp_DanhSachhPhieuNhap");
        }
    
        public virtual ObjectResult<sp_DanhSachTonKho_Result> sp_DanhSachTonKho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachTonKho_Result>("sp_DanhSachTonKho");
        }
    
        public virtual int sp_DELETE_DONDH(Nullable<int> mADH)
        {
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_DONDH", mADHParameter);
        }
    
        public virtual int sp_DELETE_KHACHHANG(Nullable<int> mAKH)
        {
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_KHACHHANG", mAKHParameter);
        }
    
        public virtual int sp_DELETE_LOAISP(Nullable<int> mALOAI)
        {
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_LOAISP", mALOAIParameter);
        }
    
        public virtual int sp_DELETE_NHACC(Nullable<int> mACC)
        {
            var mACCParameter = mACC.HasValue ?
                new ObjectParameter("MACC", mACC) :
                new ObjectParameter("MACC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_NHACC", mACCParameter);
        }
    
        public virtual int sp_DELETE_NHANVIEN(Nullable<int> mANV)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_NHANVIEN", mANVParameter);
        }
    
        public virtual int sp_DELETE_NHASX(Nullable<int> mASX)
        {
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_NHASX", mASXParameter);
        }
    
        public virtual int sp_DELETE_PHIEUNHAP(Nullable<int> mAPN, Nullable<int> mASP)
        {
            var mAPNParameter = mAPN.HasValue ?
                new ObjectParameter("MAPN", mAPN) :
                new ObjectParameter("MAPN", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_PHIEUNHAP", mAPNParameter, mASPParameter);
        }
    
        public virtual int sp_DELETE_PHIEUXUAT(Nullable<int> mAPX, Nullable<int> mASP)
        {
            var mAPXParameter = mAPX.HasValue ?
                new ObjectParameter("MAPX", mAPX) :
                new ObjectParameter("MAPX", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_PHIEUXUAT", mAPXParameter, mASPParameter);
        }
    
        public virtual int sp_DELETE_SANPHAM(Nullable<int> mASP)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DELETE_SANPHAM", mASPParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_HienThiDanhSachDonDhChoPhieuNhap_Result> sp_HienThiDanhSachDonDhChoPhieuNhap(Nullable<int> mADH)
        {
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiDanhSachDonDhChoPhieuNhap_Result>("sp_HienThiDanhSachDonDhChoPhieuNhap", mADHParameter);
        }
    
        public virtual ObjectResult<string> sp_HienThiDonDatHang(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_HienThiDonDatHang", searchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_HienThiSlDhChoBangPhieuNhap(Nullable<int> mADH, Nullable<int> mASP)
        {
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_HienThiSlDhChoBangPhieuNhap", mADHParameter, mASPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_HienThiTongSltTheoMaSp(Nullable<int> mASP)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_HienThiTongSltTheoMaSp", mASPParameter);
        }
    
        public virtual int sp_INSERT_CTCN_UPDATE_CHUCNANG(string mAQH, Nullable<bool> dANHMUC, Nullable<bool> qUANLYBANHANG, Nullable<bool> tHONGKE, Nullable<bool> sAOLUU, Nullable<bool> hELP, string mACN, string tENCHUCNANG, Nullable<bool> iNSERTS, Nullable<bool> uPDATES, Nullable<bool> dELETES, Nullable<bool> sEARCHS, Nullable<bool> pRINTS)
        {
            var mAQHParameter = mAQH != null ?
                new ObjectParameter("MAQH", mAQH) :
                new ObjectParameter("MAQH", typeof(string));
    
            var dANHMUCParameter = dANHMUC.HasValue ?
                new ObjectParameter("DANHMUC", dANHMUC) :
                new ObjectParameter("DANHMUC", typeof(bool));
    
            var qUANLYBANHANGParameter = qUANLYBANHANG.HasValue ?
                new ObjectParameter("QUANLYBANHANG", qUANLYBANHANG) :
                new ObjectParameter("QUANLYBANHANG", typeof(bool));
    
            var tHONGKEParameter = tHONGKE.HasValue ?
                new ObjectParameter("THONGKE", tHONGKE) :
                new ObjectParameter("THONGKE", typeof(bool));
    
            var sAOLUUParameter = sAOLUU.HasValue ?
                new ObjectParameter("SAOLUU", sAOLUU) :
                new ObjectParameter("SAOLUU", typeof(bool));
    
            var hELPParameter = hELP.HasValue ?
                new ObjectParameter("HELP", hELP) :
                new ObjectParameter("HELP", typeof(bool));
    
            var mACNParameter = mACN != null ?
                new ObjectParameter("MACN", mACN) :
                new ObjectParameter("MACN", typeof(string));
    
            var tENCHUCNANGParameter = tENCHUCNANG != null ?
                new ObjectParameter("TENCHUCNANG", tENCHUCNANG) :
                new ObjectParameter("TENCHUCNANG", typeof(string));
    
            var iNSERTSParameter = iNSERTS.HasValue ?
                new ObjectParameter("INSERTS", iNSERTS) :
                new ObjectParameter("INSERTS", typeof(bool));
    
            var uPDATESParameter = uPDATES.HasValue ?
                new ObjectParameter("UPDATES", uPDATES) :
                new ObjectParameter("UPDATES", typeof(bool));
    
            var dELETESParameter = dELETES.HasValue ?
                new ObjectParameter("DELETES", dELETES) :
                new ObjectParameter("DELETES", typeof(bool));
    
            var sEARCHSParameter = sEARCHS.HasValue ?
                new ObjectParameter("SEARCHS", sEARCHS) :
                new ObjectParameter("SEARCHS", typeof(bool));
    
            var pRINTSParameter = pRINTS.HasValue ?
                new ObjectParameter("PRINTS", pRINTS) :
                new ObjectParameter("PRINTS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_INSERT_CTCN_UPDATE_CHUCNANG", mAQHParameter, dANHMUCParameter, qUANLYBANHANGParameter, tHONGKEParameter, sAOLUUParameter, hELPParameter, mACNParameter, tENCHUCNANGParameter, iNSERTSParameter, uPDATESParameter, dELETESParameter, sEARCHSParameter, pRINTSParameter);
        }
    
        public virtual int sp_Insert_CTPQ(Nullable<int> iD, string mAQH)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mAQHParameter = mAQH != null ?
                new ObjectParameter("MAQH", mAQH) :
                new ObjectParameter("MAQH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_CTPQ", iDParameter, mAQHParameter);
        }
    
        public virtual int sp_Insert_DONDH(Nullable<int> mANV, Nullable<int> mACC, Nullable<int> mASP, Nullable<int> sLDH, Nullable<System.DateTime> nGDH)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mACCParameter = mACC.HasValue ?
                new ObjectParameter("MACC", mACC) :
                new ObjectParameter("MACC", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLDHParameter = sLDH.HasValue ?
                new ObjectParameter("SLDH", sLDH) :
                new ObjectParameter("SLDH", typeof(int));
    
            var nGDHParameter = nGDH.HasValue ?
                new ObjectParameter("NGDH", nGDH) :
                new ObjectParameter("NGDH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_DONDH", mANVParameter, mACCParameter, mASPParameter, sLDHParameter, nGDHParameter);
        }
    
        public virtual int sp_Insert_KHACHHANG(string tENKH, Nullable<System.DateTime> nGAYSINH, string gT, Nullable<int> sDT, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYDK)
        {
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYDKParameter = nGAYDK.HasValue ?
                new ObjectParameter("NGAYDK", nGAYDK) :
                new ObjectParameter("NGAYDK", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_KHACHHANG", tENKHParameter, nGAYSINHParameter, gTParameter, sDTParameter, mAILParameter, dIACHIParameter, nGAYDKParameter);
        }
    
        public virtual int sp_Insert_LOAISP(string tENLOAI, string dVT)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_LOAISP", tENLOAIParameter, dVTParameter);
        }
    
        public virtual int sp_Insert_NHACC(string tENCC, string dIACHI, Nullable<int> sDT)
        {
            var tENCCParameter = tENCC != null ?
                new ObjectParameter("TENCC", tENCC) :
                new ObjectParameter("TENCC", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_NHACC", tENCCParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual int sp_Insert_NhanVien(string hoten, Nullable<System.DateTime> ngaySinh, string gt, Nullable<int> sdt, string mail, string diachi, Nullable<System.DateTime> ngaylam)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gtParameter = gt != null ?
                new ObjectParameter("Gt", gt) :
                new ObjectParameter("Gt", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var ngaylamParameter = ngaylam.HasValue ?
                new ObjectParameter("Ngaylam", ngaylam) :
                new ObjectParameter("Ngaylam", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_NhanVien", hotenParameter, ngaySinhParameter, gtParameter, sdtParameter, mailParameter, diachiParameter, ngaylamParameter);
        }
    
        public virtual int sp_Insert_NHASX(string tENSX, string qUOCGIA)
        {
            var tENSXParameter = tENSX != null ?
                new ObjectParameter("TENSX", tENSX) :
                new ObjectParameter("TENSX", typeof(string));
    
            var qUOCGIAParameter = qUOCGIA != null ?
                new ObjectParameter("QUOCGIA", qUOCGIA) :
                new ObjectParameter("QUOCGIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_NHASX", tENSXParameter, qUOCGIAParameter);
        }
    
        public virtual int sp_Insert_PHANQUYEN(string mAQH, string tENQH, string gHICHU)
        {
            var mAQHParameter = mAQH != null ?
                new ObjectParameter("MAQH", mAQH) :
                new ObjectParameter("MAQH", typeof(string));
    
            var tENQHParameter = tENQH != null ?
                new ObjectParameter("TENQH", tENQH) :
                new ObjectParameter("TENQH", typeof(string));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_PHANQUYEN", mAQHParameter, tENQHParameter, gHICHUParameter);
        }
    
        public virtual int sp_Insert_PHIEUNHAP(Nullable<int> mANV, Nullable<int> mADH, Nullable<int> mASP, Nullable<int> sLN, Nullable<decimal> dONGIA, Nullable<System.DateTime> nGAYNHAP)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLNParameter = sLN.HasValue ?
                new ObjectParameter("SLN", sLN) :
                new ObjectParameter("SLN", typeof(int));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(decimal));
    
            var nGAYNHAPParameter = nGAYNHAP.HasValue ?
                new ObjectParameter("NGAYNHAP", nGAYNHAP) :
                new ObjectParameter("NGAYNHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_PHIEUNHAP", mANVParameter, mADHParameter, mASPParameter, sLNParameter, dONGIAParameter, nGAYNHAPParameter);
        }
    
        public virtual int sp_Insert_PHIEUXUAT(Nullable<int> mANV, Nullable<int> mAKH, Nullable<int> mASP, Nullable<int> sLX, Nullable<System.DateTime> nGAYXUAT, Nullable<float> pHANTRAM)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLXParameter = sLX.HasValue ?
                new ObjectParameter("SLX", sLX) :
                new ObjectParameter("SLX", typeof(int));
    
            var nGAYXUATParameter = nGAYXUAT.HasValue ?
                new ObjectParameter("NGAYXUAT", nGAYXUAT) :
                new ObjectParameter("NGAYXUAT", typeof(System.DateTime));
    
            var pHANTRAMParameter = pHANTRAM.HasValue ?
                new ObjectParameter("PHANTRAM", pHANTRAM) :
                new ObjectParameter("PHANTRAM", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_PHIEUXUAT", mANVParameter, mAKHParameter, mASPParameter, sLXParameter, nGAYXUATParameter, pHANTRAMParameter);
        }
    
        public virtual int sp_Insert_SANPHAM(string tENSP, Nullable<int> mASX, Nullable<int> mALOAI, Nullable<decimal> gIATHANH, string cPU, string rAM, string oCUNG, string mANHINH, string cARD, string pORTCONNECT, string hDT, string aMTHANH, string dIAQUANG, string gIAOTIEP, string wEBCAM, string pIN, string tRONGLUONG, string bAOHANH, Nullable<System.DateTime> nGAYNHAP)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var gIATHANHParameter = gIATHANH.HasValue ?
                new ObjectParameter("GIATHANH", gIATHANH) :
                new ObjectParameter("GIATHANH", typeof(decimal));
    
            var cPUParameter = cPU != null ?
                new ObjectParameter("CPU", cPU) :
                new ObjectParameter("CPU", typeof(string));
    
            var rAMParameter = rAM != null ?
                new ObjectParameter("RAM", rAM) :
                new ObjectParameter("RAM", typeof(string));
    
            var oCUNGParameter = oCUNG != null ?
                new ObjectParameter("OCUNG", oCUNG) :
                new ObjectParameter("OCUNG", typeof(string));
    
            var mANHINHParameter = mANHINH != null ?
                new ObjectParameter("MANHINH", mANHINH) :
                new ObjectParameter("MANHINH", typeof(string));
    
            var cARDParameter = cARD != null ?
                new ObjectParameter("CARD", cARD) :
                new ObjectParameter("CARD", typeof(string));
    
            var pORTCONNECTParameter = pORTCONNECT != null ?
                new ObjectParameter("PORTCONNECT", pORTCONNECT) :
                new ObjectParameter("PORTCONNECT", typeof(string));
    
            var hDTParameter = hDT != null ?
                new ObjectParameter("HDT", hDT) :
                new ObjectParameter("HDT", typeof(string));
    
            var aMTHANHParameter = aMTHANH != null ?
                new ObjectParameter("AMTHANH", aMTHANH) :
                new ObjectParameter("AMTHANH", typeof(string));
    
            var dIAQUANGParameter = dIAQUANG != null ?
                new ObjectParameter("DIAQUANG", dIAQUANG) :
                new ObjectParameter("DIAQUANG", typeof(string));
    
            var gIAOTIEPParameter = gIAOTIEP != null ?
                new ObjectParameter("GIAOTIEP", gIAOTIEP) :
                new ObjectParameter("GIAOTIEP", typeof(string));
    
            var wEBCAMParameter = wEBCAM != null ?
                new ObjectParameter("WEBCAM", wEBCAM) :
                new ObjectParameter("WEBCAM", typeof(string));
    
            var pINParameter = pIN != null ?
                new ObjectParameter("PIN", pIN) :
                new ObjectParameter("PIN", typeof(string));
    
            var tRONGLUONGParameter = tRONGLUONG != null ?
                new ObjectParameter("TRONGLUONG", tRONGLUONG) :
                new ObjectParameter("TRONGLUONG", typeof(string));
    
            var bAOHANHParameter = bAOHANH != null ?
                new ObjectParameter("BAOHANH", bAOHANH) :
                new ObjectParameter("BAOHANH", typeof(string));
    
            var nGAYNHAPParameter = nGAYNHAP.HasValue ?
                new ObjectParameter("NGAYNHAP", nGAYNHAP) :
                new ObjectParameter("NGAYNHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_SANPHAM", tENSPParameter, mASXParameter, mALOAIParameter, gIATHANHParameter, cPUParameter, rAMParameter, oCUNGParameter, mANHINHParameter, cARDParameter, pORTCONNECTParameter, hDTParameter, aMTHANHParameter, dIAQUANGParameter, gIAOTIEPParameter, wEBCAMParameter, pINParameter, tRONGLUONGParameter, bAOHANHParameter, nGAYNHAPParameter);
        }
    
        public virtual int sp_Insert_TaiKhoan_NhanVien(Nullable<int> iD, Nullable<int> pass)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var passParameter = pass.HasValue ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_TaiKhoan_NhanVien", iDParameter, passParameter);
        }
    
        public virtual int sp_Insert_TONKHO(Nullable<System.DateTime> nGAYTHANG, Nullable<int> mASP, Nullable<int> sLD, Nullable<int> sLN, Nullable<int> sLX)
        {
            var nGAYTHANGParameter = nGAYTHANG.HasValue ?
                new ObjectParameter("NGAYTHANG", nGAYTHANG) :
                new ObjectParameter("NGAYTHANG", typeof(System.DateTime));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLDParameter = sLD.HasValue ?
                new ObjectParameter("SLD", sLD) :
                new ObjectParameter("SLD", typeof(int));
    
            var sLNParameter = sLN.HasValue ?
                new ObjectParameter("SLN", sLN) :
                new ObjectParameter("SLN", typeof(int));
    
            var sLXParameter = sLX.HasValue ?
                new ObjectParameter("SLX", sLX) :
                new ObjectParameter("SLX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_TONKHO", nGAYTHANGParameter, mASPParameter, sLDParameter, sLNParameter, sLXParameter);
        }
    
        public virtual int sp_PHANQUYEN_NHANVIEN(Nullable<int> iD, string mAQH)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mAQHParameter = mAQH != null ?
                new ObjectParameter("MAQH", mAQH) :
                new ObjectParameter("MAQH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PHANQUYEN_NHANVIEN", iDParameter, mAQHParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_Search_HienThiThongTinTaiKhoanNhanVien_Result> sp_Search_HienThiThongTinTaiKhoanNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_HienThiThongTinTaiKhoanNhanVien_Result>("sp_Search_HienThiThongTinTaiKhoanNhanVien");
        }
    
        public virtual ObjectResult<sp_Search_SanPham_Theo_MaSp_Result> sp_Search_SanPham_Theo_MaSp(Nullable<int> masp)
        {
            var maspParameter = masp.HasValue ?
                new ObjectParameter("Masp", masp) :
                new ObjectParameter("Masp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_SanPham_Theo_MaSp_Result>("sp_Search_SanPham_Theo_MaSp", maspParameter);
        }
    
        public virtual ObjectResult<sp_Search_ThongTinTaiKhoanNhanVien_Result> sp_Search_ThongTinTaiKhoanNhanVien(Nullable<int> iD, Nullable<int> pASS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pASSParameter = pASS.HasValue ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_ThongTinTaiKhoanNhanVien_Result>("sp_Search_ThongTinTaiKhoanNhanVien", iDParameter, pASSParameter);
        }
    
        public virtual ObjectResult<sp_SearchTaiKhoanNhanVienTheoMaQh_Result> sp_SearchTaiKhoanNhanVienTheoMaQh(string mAQH)
        {
            var mAQHParameter = mAQH != null ?
                new ObjectParameter("MAQH", mAQH) :
                new ObjectParameter("MAQH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchTaiKhoanNhanVienTheoMaQh_Result>("sp_SearchTaiKhoanNhanVienTheoMaQh", mAQHParameter);
        }
    
        public virtual ObjectResult<sp_SELECT_CHUCNANG_Result> sp_SELECT_CHUCNANG(string mACN, string tENCHUCNANG)
        {
            var mACNParameter = mACN != null ?
                new ObjectParameter("MACN", mACN) :
                new ObjectParameter("MACN", typeof(string));
    
            var tENCHUCNANGParameter = tENCHUCNANG != null ?
                new ObjectParameter("TENCHUCNANG", tENCHUCNANG) :
                new ObjectParameter("TENCHUCNANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SELECT_CHUCNANG_Result>("sp_SELECT_CHUCNANG", mACNParameter, tENCHUCNANGParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Select_ThongTinDonHangChoPhieuNhap(Nullable<int> mADH)
        {
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Select_ThongTinDonHangChoPhieuNhap", mADHParameter);
        }
    
        public virtual ObjectResult<sp_Select_ThongTinPhieuXuatTheoMaDh_Result> sp_Select_ThongTinPhieuXuatTheoMaDh(Nullable<int> mADH)
        {
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_ThongTinPhieuXuatTheoMaDh_Result>("sp_Select_ThongTinPhieuXuatTheoMaDh", mADHParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDonDatHang_Result> sp_ThongKeDonDatHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDonDatHang_Result>("sp_ThongKeDonDatHang");
        }
    
        public virtual ObjectResult<sp_ThongKeDonDatHangTheoNgayThang_Result> sp_ThongKeDonDatHangTheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDonDatHangTheoNgayThang_Result>("sp_ThongKeDonDatHangTheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDonHangTheoNhaSx_Result> sp_ThongKeDonHangTheoNhaSx(string tenSx)
        {
            var tenSxParameter = tenSx != null ?
                new ObjectParameter("TenSx", tenSx) :
                new ObjectParameter("TenSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDonHangTheoNhaSx_Result>("sp_ThongKeDonHangTheoNhaSx", tenSxParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDonHangTheoTenLoai_Result> sp_ThongKeDonHangTheoTenLoai(string tenLoai)
        {
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDonHangTheoTenLoai_Result>("sp_ThongKeDonHangTheoTenLoai", tenLoaiParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuNhap_Result> sp_ThongKePhieuNhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuNhap_Result>("sp_ThongKePhieuNhap");
        }
    
        public virtual ObjectResult<sp_ThongKePhieuNhapTheoLoaiSp_Result> sp_ThongKePhieuNhapTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuNhapTheoLoaiSp_Result>("sp_ThongKePhieuNhapTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuNhapTheoNgayThang_Result> sp_ThongKePhieuNhapTheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuNhapTheoNgayThang_Result>("sp_ThongKePhieuNhapTheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuNhapTheoNhaCungCap_Result> sp_ThongKePhieuNhapTheoNhaCungCap(string tenCc)
        {
            var tenCcParameter = tenCc != null ?
                new ObjectParameter("TenCc", tenCc) :
                new ObjectParameter("TenCc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuNhapTheoNhaCungCap_Result>("sp_ThongKePhieuNhapTheoNhaCungCap", tenCcParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuXuat_Result> sp_ThongKePhieuXuat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuXuat_Result>("sp_ThongKePhieuXuat");
        }
    
        public virtual ObjectResult<sp_ThongKePhieuXuatTtheoLoaiSp_Result> sp_ThongKePhieuXuatTtheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuXuatTtheoLoaiSp_Result>("sp_ThongKePhieuXuatTtheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuXuatTtheoNgayThang_Result> sp_ThongKePhieuXuatTtheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuXuatTtheoNgayThang_Result>("sp_ThongKePhieuXuatTtheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuXuatTtheoNhaSx_Result> sp_ThongKePhieuXuatTtheoNhaSx(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuXuatTtheoNhaSx_Result>("sp_ThongKePhieuXuatTtheoNhaSx", nhaSxParameter);
        }
    
        public virtual ObjectResult<sp_ThongKePhieuXuatTtheoTenSp_Result> sp_ThongKePhieuXuatTtheoTenSp(string tenSp)
        {
            var tenSpParameter = tenSp != null ?
                new ObjectParameter("TenSp", tenSp) :
                new ObjectParameter("TenSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKePhieuXuatTtheoTenSp_Result>("sp_ThongKePhieuXuatTtheoTenSp", tenSpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ThongKeTongSoDoDhTheoMaSp(Nullable<int> masp)
        {
            var maspParameter = masp.HasValue ?
                new ObjectParameter("Masp", masp) :
                new ObjectParameter("Masp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ThongKeTongSoDoDhTheoMaSp", maspParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeTonKhoTheoLoaiSp_Result> sp_ThongKeTonKhoTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeTonKhoTheoLoaiSp_Result>("sp_ThongKeTonKhoTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeTonKhoTheoNgayThang_Result> sp_ThongKeTonKhoTheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeTonKhoTheoNgayThang_Result>("sp_ThongKeTonKhoTheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeTonKhoTheoNhaSx_Result> sp_ThongKeTonKhoTheoNhaSx(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeTonKhoTheoNhaSx_Result>("sp_ThongKeTonKhoTheoNhaSx", nhaSxParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemDonDatHang_Result> sp_TimKiemDonDatHang(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemDonDatHang_Result>("sp_TimKiemDonDatHang", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemKhachHang_Result> sp_TimKiemKhachHang(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemKhachHang_Result>("sp_TimKiemKhachHang", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemLoaiSanPham_Result> sp_TimKiemLoaiSanPham(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemLoaiSanPham_Result>("sp_TimKiemLoaiSanPham", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemNhaCungCap_Result> sp_TimKiemNhaCungCap(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemNhaCungCap_Result>("sp_TimKiemNhaCungCap", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemNhanVien_Result> sp_TimKiemNhanVien(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemNhanVien_Result>("sp_TimKiemNhanVien", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemNhaSanXuat_Result> sp_TimKiemNhaSanXuat(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemNhaSanXuat_Result>("sp_TimKiemNhaSanXuat", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemPhieuNhap_Result> sp_TimKiemPhieuNhap(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemPhieuNhap_Result>("sp_TimKiemPhieuNhap", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemPhieuXuat_Result> sp_TimKiemPhieuXuat(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemPhieuXuat_Result>("sp_TimKiemPhieuXuat", searchParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemSanPham_Result> sp_TimKiemSanPham(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemSanPham_Result>("sp_TimKiemSanPham", searchParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhhTongThanhTienPHieuXuatTheoNhaSx(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhhTongThanhTienPHieuXuatTheoNhaSx", nhaSxParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTienThua(Nullable<int> mAPX, Nullable<decimal> tIENKHACHDUA)
        {
            var mAPXParameter = mAPX.HasValue ?
                new ObjectParameter("MAPX", mAPX) :
                new ObjectParameter("MAPX", typeof(int));
    
            var tIENKHACHDUAParameter = tIENKHACHDUA.HasValue ?
                new ObjectParameter("TIENKHACHDUA", tIENKHACHDUA) :
                new ObjectParameter("TIENKHACHDUA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTienThua", mAPXParameter, tIENKHACHDUAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlDonDhTheoLoaiSp(string tenLoai)
        {
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlDonDhTheoLoaiSp", tenLoaiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlDonDhTheoNgayDatHang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlDonDhTheoNgayDatHang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlDonDhTheoNhaSx(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlDonDhTheoNhaSx", nhaSxParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSltChoTonKho(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSltChoTonKho", nhaSxParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSltChoTonKhoTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSltChoTonKhoTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSltChoTonKhoTheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSltChoTonKhoTheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlxPHieuXuatTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlxPHieuXuatTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlxPhieuXuatTheoNgayXuat(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlxPhieuXuatTheoNgayXuat", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSlxPhieuXuatTheoNhaSx(string nhaSx)
        {
            var nhaSxParameter = nhaSx != null ?
                new ObjectParameter("NhaSx", nhaSx) :
                new ObjectParameter("NhaSx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSlxPhieuXuatTheoNhaSx", nhaSxParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuConNhapTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuConNhapTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuConNhapTheoNgayNhap(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuConNhapTheoNgayNhap", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuConNhapTheoNhaCungCap(string nhaCc)
        {
            var nhaCcParameter = nhaCc != null ?
                new ObjectParameter("NhaCc", nhaCc) :
                new ObjectParameter("NhaCc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuConNhapTheoNhaCungCap", nhaCcParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuNhapTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuNhapTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuNhapTheoNgayThang(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuNhapTheoNgayThang", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TinhTongSoPhieuNhapTheoNhaCungCap(string nhaCc)
        {
            var nhaCcParameter = nhaCc != null ?
                new ObjectParameter("NhaCc", nhaCc) :
                new ObjectParameter("NhaCc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TinhTongSoPhieuNhapTheoNhaCungCap", nhaCcParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongThanhTienPhieuNhapTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongThanhTienPhieuNhapTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongThanhTienPhieuNhapTheoNgayNhap(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongThanhTienPhieuNhapTheoNgayNhap", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongThanhTienPhieuNhapTheoNhaCc(string nhaCc)
        {
            var nhaCcParameter = nhaCc != null ?
                new ObjectParameter("NhaCc", nhaCc) :
                new ObjectParameter("NhaCc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongThanhTienPhieuNhapTheoNhaCc", nhaCcParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongThanhTienPHieuXuatTheoLoaiSp(string loaiSp)
        {
            var loaiSpParameter = loaiSp != null ?
                new ObjectParameter("LoaiSp", loaiSp) :
                new ObjectParameter("LoaiSp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongThanhTienPHieuXuatTheoLoaiSp", loaiSpParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongThanhTienPhieuXuatTheoNgayXuat(Nullable<System.DateTime> dateTimesOne, Nullable<System.DateTime> dateTimesTwo)
        {
            var dateTimesOneParameter = dateTimesOne.HasValue ?
                new ObjectParameter("DateTimesOne", dateTimesOne) :
                new ObjectParameter("DateTimesOne", typeof(System.DateTime));
    
            var dateTimesTwoParameter = dateTimesTwo.HasValue ?
                new ObjectParameter("DateTimesTwo", dateTimesTwo) :
                new ObjectParameter("DateTimesTwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongThanhTienPhieuXuatTheoNgayXuat", dateTimesOneParameter, dateTimesTwoParameter);
        }
    
        public virtual int sp_UPDATE_DONDH(Nullable<int> mANV, Nullable<int> mACC, Nullable<int> mASP, Nullable<int> sLDH, Nullable<System.DateTime> nGDH, Nullable<int> mADH)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mACCParameter = mACC.HasValue ?
                new ObjectParameter("MACC", mACC) :
                new ObjectParameter("MACC", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLDHParameter = sLDH.HasValue ?
                new ObjectParameter("SLDH", sLDH) :
                new ObjectParameter("SLDH", typeof(int));
    
            var nGDHParameter = nGDH.HasValue ?
                new ObjectParameter("NGDH", nGDH) :
                new ObjectParameter("NGDH", typeof(System.DateTime));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_DONDH", mANVParameter, mACCParameter, mASPParameter, sLDHParameter, nGDHParameter, mADHParameter);
        }
    
        public virtual int sp_UPDATE_KHACHHANG(string tENKH, Nullable<System.DateTime> nGAYSINH, string gT, Nullable<int> sDT, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYDK, Nullable<int> mAKH)
        {
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYDKParameter = nGAYDK.HasValue ?
                new ObjectParameter("NGAYDK", nGAYDK) :
                new ObjectParameter("NGAYDK", typeof(System.DateTime));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_KHACHHANG", tENKHParameter, nGAYSINHParameter, gTParameter, sDTParameter, mAILParameter, dIACHIParameter, nGAYDKParameter, mAKHParameter);
        }
    
        public virtual int sp_UPDATE_LOAISP(string tENLOAI, string dVT, Nullable<int> mALOAI)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_LOAISP", tENLOAIParameter, dVTParameter, mALOAIParameter);
        }
    
        public virtual int sp_UPDATE_NHACC(string tENCC, string dIACHI, Nullable<int> sDT, Nullable<int> mACC)
        {
            var tENCCParameter = tENCC != null ?
                new ObjectParameter("TENCC", tENCC) :
                new ObjectParameter("TENCC", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            var mACCParameter = mACC.HasValue ?
                new ObjectParameter("MACC", mACC) :
                new ObjectParameter("MACC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_NHACC", tENCCParameter, dIACHIParameter, sDTParameter, mACCParameter);
        }
    
        public virtual int sp_UPDATE_NHANVIEN(string hOTEN, Nullable<System.DateTime> nGAYSINH, string gT, Nullable<int> sDT, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYLAM, Nullable<int> mANV)
        {
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYLAMParameter = nGAYLAM.HasValue ?
                new ObjectParameter("NGAYLAM", nGAYLAM) :
                new ObjectParameter("NGAYLAM", typeof(System.DateTime));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_NHANVIEN", hOTENParameter, nGAYSINHParameter, gTParameter, sDTParameter, mAILParameter, dIACHIParameter, nGAYLAMParameter, mANVParameter);
        }
    
        public virtual int sp_UPDATE_NHASX(string tENSX, string qUOCGIA, Nullable<int> mASX)
        {
            var tENSXParameter = tENSX != null ?
                new ObjectParameter("TENSX", tENSX) :
                new ObjectParameter("TENSX", typeof(string));
    
            var qUOCGIAParameter = qUOCGIA != null ?
                new ObjectParameter("QUOCGIA", qUOCGIA) :
                new ObjectParameter("QUOCGIA", typeof(string));
    
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_NHASX", tENSXParameter, qUOCGIAParameter, mASXParameter);
        }
    
        public virtual int sp_UPDATE_PHIEUNHAP(Nullable<int> mANV, Nullable<int> mADH, Nullable<int> mASP, Nullable<int> sLN, Nullable<decimal> dONGIA, Nullable<System.DateTime> nGAYNHAP, Nullable<int> mAPN)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLNParameter = sLN.HasValue ?
                new ObjectParameter("SLN", sLN) :
                new ObjectParameter("SLN", typeof(int));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(decimal));
    
            var nGAYNHAPParameter = nGAYNHAP.HasValue ?
                new ObjectParameter("NGAYNHAP", nGAYNHAP) :
                new ObjectParameter("NGAYNHAP", typeof(System.DateTime));
    
            var mAPNParameter = mAPN.HasValue ?
                new ObjectParameter("MAPN", mAPN) :
                new ObjectParameter("MAPN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_PHIEUNHAP", mANVParameter, mADHParameter, mASPParameter, sLNParameter, dONGIAParameter, nGAYNHAPParameter, mAPNParameter);
        }
    
        public virtual int sp_UPDATE_PHIEUXUAT(Nullable<int> mANV, Nullable<int> mAKH, Nullable<int> mASP, Nullable<int> sLX, Nullable<float> pHANTRAM, Nullable<decimal> tHANHTIEN, Nullable<System.DateTime> nGAYXUAT, Nullable<int> mAPX)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sLXParameter = sLX.HasValue ?
                new ObjectParameter("SLX", sLX) :
                new ObjectParameter("SLX", typeof(int));
    
            var pHANTRAMParameter = pHANTRAM.HasValue ?
                new ObjectParameter("PHANTRAM", pHANTRAM) :
                new ObjectParameter("PHANTRAM", typeof(float));
    
            var tHANHTIENParameter = tHANHTIEN.HasValue ?
                new ObjectParameter("THANHTIEN", tHANHTIEN) :
                new ObjectParameter("THANHTIEN", typeof(decimal));
    
            var nGAYXUATParameter = nGAYXUAT.HasValue ?
                new ObjectParameter("NGAYXUAT", nGAYXUAT) :
                new ObjectParameter("NGAYXUAT", typeof(System.DateTime));
    
            var mAPXParameter = mAPX.HasValue ?
                new ObjectParameter("MAPX", mAPX) :
                new ObjectParameter("MAPX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_PHIEUXUAT", mANVParameter, mAKHParameter, mASPParameter, sLXParameter, pHANTRAMParameter, tHANHTIENParameter, nGAYXUATParameter, mAPXParameter);
        }
    
        public virtual int sp_UPDATE_SANPHAM(string tENSP, Nullable<int> mASX, Nullable<int> mALOAI, Nullable<decimal> gIATHANH, string cPU, string rAM, string oCUNG, string mANHINH, string cARD, string pORTCONNECT, string hDT, string aMTHANH, string dIAQUANG, string gIAOTIEP, string wEBCAM, string pIN, string tRONGLUONG, string bAOHANH, Nullable<int> mASP)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var gIATHANHParameter = gIATHANH.HasValue ?
                new ObjectParameter("GIATHANH", gIATHANH) :
                new ObjectParameter("GIATHANH", typeof(decimal));
    
            var cPUParameter = cPU != null ?
                new ObjectParameter("CPU", cPU) :
                new ObjectParameter("CPU", typeof(string));
    
            var rAMParameter = rAM != null ?
                new ObjectParameter("RAM", rAM) :
                new ObjectParameter("RAM", typeof(string));
    
            var oCUNGParameter = oCUNG != null ?
                new ObjectParameter("OCUNG", oCUNG) :
                new ObjectParameter("OCUNG", typeof(string));
    
            var mANHINHParameter = mANHINH != null ?
                new ObjectParameter("MANHINH", mANHINH) :
                new ObjectParameter("MANHINH", typeof(string));
    
            var cARDParameter = cARD != null ?
                new ObjectParameter("CARD", cARD) :
                new ObjectParameter("CARD", typeof(string));
    
            var pORTCONNECTParameter = pORTCONNECT != null ?
                new ObjectParameter("PORTCONNECT", pORTCONNECT) :
                new ObjectParameter("PORTCONNECT", typeof(string));
    
            var hDTParameter = hDT != null ?
                new ObjectParameter("HDT", hDT) :
                new ObjectParameter("HDT", typeof(string));
    
            var aMTHANHParameter = aMTHANH != null ?
                new ObjectParameter("AMTHANH", aMTHANH) :
                new ObjectParameter("AMTHANH", typeof(string));
    
            var dIAQUANGParameter = dIAQUANG != null ?
                new ObjectParameter("DIAQUANG", dIAQUANG) :
                new ObjectParameter("DIAQUANG", typeof(string));
    
            var gIAOTIEPParameter = gIAOTIEP != null ?
                new ObjectParameter("GIAOTIEP", gIAOTIEP) :
                new ObjectParameter("GIAOTIEP", typeof(string));
    
            var wEBCAMParameter = wEBCAM != null ?
                new ObjectParameter("WEBCAM", wEBCAM) :
                new ObjectParameter("WEBCAM", typeof(string));
    
            var pINParameter = pIN != null ?
                new ObjectParameter("PIN", pIN) :
                new ObjectParameter("PIN", typeof(string));
    
            var tRONGLUONGParameter = tRONGLUONG != null ?
                new ObjectParameter("TRONGLUONG", tRONGLUONG) :
                new ObjectParameter("TRONGLUONG", typeof(string));
    
            var bAOHANHParameter = bAOHANH != null ?
                new ObjectParameter("BAOHANH", bAOHANH) :
                new ObjectParameter("BAOHANH", typeof(string));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_SANPHAM", tENSPParameter, mASXParameter, mALOAIParameter, gIATHANHParameter, cPUParameter, rAMParameter, oCUNGParameter, mANHINHParameter, cARDParameter, pORTCONNECTParameter, hDTParameter, aMTHANHParameter, dIAQUANGParameter, gIAOTIEPParameter, wEBCAMParameter, pINParameter, tRONGLUONGParameter, bAOHANHParameter, mASPParameter);
        }
    
        public virtual int sp_UPDATE_TAIKHOAN(Nullable<int> iD, Nullable<int> pASS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pASSParameter = pASS.HasValue ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_TAIKHOAN", iDParameter, pASSParameter);
        }
    
        public virtual int sp_UPDATE_TONKHO(Nullable<int> tONGSLD, Nullable<int> mASP)
        {
            var tONGSLDParameter = tONGSLD.HasValue ?
                new ObjectParameter("TONGSLD", tONGSLD) :
                new ObjectParameter("TONGSLD", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATE_TONKHO", tONGSLDParameter, mASPParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
