//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhSachSanPhams
    {
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> GIATHANH { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string OCUNG { get; set; }
        public string CARDMANHINH { get; set; }
        public string MANHINH { get; set; }
        public string PORTCONNECT { get; set; }
        public string HDT { get; set; }
        public string AMTHANH { get; set; }
        public string DIAQUANG { get; set; }
        public string GIAOTIEPMANG { get; set; }
        public string WEBCAM { get; set; }
        public string PIN { get; set; }
        public string TRONGLUONG { get; set; }
        public string BAOHANH { get; set; }
        public string TENLOAI { get; set; }
        public string TENSX { get; set; }
    }
}
