//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhSachKhachHang
    {
        public int MAKH { get; set; }
        public string TENKH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GT { get; set; }
        public Nullable<int> SDT { get; set; }
        public string MAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYDK { get; set; }
    }
}
