//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhSachDonDatHang
    {
        public int MADH { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MACC { get; set; }
        public Nullable<System.DateTime> NGDH { get; set; }
        public string HOTEN { get; set; }
        public string TENCC { get; set; }
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SLDH { get; set; }
    }
}
