//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhSachPhieuNhap
    {
        public int MAPN { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> MADH { get; set; }
        public string HOTEN { get; set; }
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SLN { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    }
}
