//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhieuXuatKhachHang
    {
        public int MAPX { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public string TENKH { get; set; }
        public string MAIL { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DIACHI { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SLX { get; set; }
        public Nullable<decimal> GIATHANH { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<float> PHANTRAM { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    }
}
